config/routes.rb
Rails.application.routes.draw do

  post 'login' => 'authentication#login'
  use_doorkeeper
  get 'welcome/index'

  resources :previews

  resources :notes

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", sessions: 'users/sessions', registrations: 'users/registrations' }

  root 'welcome#index'

end

app/models/note.rb
class Note < ActiveRecord::Base
  validates :title, presence: true
  validate :content_should_have_more_words_than_title
  belongs_to :user
  def content_should_have_more_words_than_title
    unless title.to_s.split.size < content.to_s.split.size 
      errors.add(:content, 'Number of words in content should be more than the number of words in title')
    end
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /notes
  # GET /notes.json
  def index
		@users = User.order(:created_at)
		if current_user.equal? @users[0] 
			@notes = Note.connection.select_all('SELECT n.id, n.title, n.content, u.email from notes n join users u on u.id = n.user_id ORDER BY n.created_at').rows
		else
      @notes = Note.all
		end
    respond_to do |format|
    	format.html { }
	    format.xml {
		    @users = User.order(:created_at)
		    if @users.first == current_user then
			  render xml: @notes
		    else
			    return head(:unauthorized)
		    end
	    }
        format.json { }
    end
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
    @note = Note.find(params[:id])
    respond_to do |format|
      format.html { }
      # from http://stackoverflow.com/a/7293155/783412
      format.pdf {
	      pdf = Prawn::Document.new
        pdf.text @note.content
        send_data pdf.render, :filename => "#{@note.hash}.pdf", :type => "application/pdf", :disposition => 'inline' 
      }
    end
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)
    @note[:user_id] = current_user.id

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:content, :title, :user)
    end
end

app/helpers/notes_helper.rb
require 'odyssey'

module NotesHelper
  def admin?
    current_user.id == 1
  end

  def score(content)
    Rails.logger.debug("#{content} should now be plaintext")
    Odyssey.flesch_kincaid_re(content, false)
  end
end

app/views/notes/_form.html.erb
<%= form_for(@note, html: { class: "edit_post form-inline" }) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation" class="has-error">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul class="list-unstyled">
      <% @note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => 'col-sm-2 control-label' %><br>
    <%= f.text_field :title, :class => 'col-sm-10 form-control' %>
  </div>
  <br>
  <div class="form-group">
    <%= f.label :content, :class => 'col-sm-2 control-label' %><br>
    <%= f.text_area :content, :class => 'col-sm-10 form-control' %>
    <p class="help-block">Markdown format</p>
  </div>
  <div class="actions">
    <% if not @content.nil?  %>
      <% link_to 'Preview', preview_path(@content) %>
    <% end %>
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<div class="col-md-12">
<h1>Editing Note</h1>
<%= render 'form' %>
<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>
</div>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>
<div class="col-md-12">
<h1>Listing Notes</h1>
</div>
<div class="col-md-4"></div><div class="col-md-4">
<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <th>Title</th>
      <% if admin? -%>
        <th>Author's E-mail</th>
      <% end -%>
      <th><%= link_to 'Flesch-Kincaid', 'https://en.wikipedia.org/wiki/Flesch%E2%80%93Kincaid_readability_tests' %> Readability score</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= link_to note.title, note, {:title => Redcarpet::Markdown.new(Redcarpet::Render::StripDown).render(note.content) } %></td>
        <% if admin? -%>
          <td><%= note.user.email %></td>
        <% end -%>
        <td><%= 
        renderer = Redcarpet::Markdown.new(Redcarpet::Render::StripDown)
        score renderer.render(note.content) %>
        <td><%= link_to 'pdf', "notes/#{note.id}.pdf" %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %></div><div class="col-md-4"></div>

app/views/notes/new.html.erb
<h1>New Note</h1>

<div class="col-md-12">
<%= render 'form' %>
<%= link_to 'Back', notes_path %>
</div>

app/views/notes/show.html.erb
<div class="alert-info" role="alert"><p id="notice"><%= notice %></p></div>
<div class="col-md-12 panel">
  <div class="panel-heading">
    <h1>
      <%= @note.title %>
    </h1>
  </div>

  <div class="panel-body">
    <%=
     markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML,
                                        no_intra_emphasis: true,
                                        fenced_code_blocks: true,
                                        disable_indented_code_blocks: true)
     markdown.render(@note.content).html_safe %>
  </div>
</div>
<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>